apiVersion: v1
kind: Service
metadata:
  name: btc-mainnet
  labels:
    app: blocksayer
spec:
  ports:
    - name: rpc
      port: 8332
      targetPort: 8332
    - name: p2p
      port: 8333
      targetPort: 8333
  selector:
    app: blocksayer
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btc-mainnet-pv
spec:
# It's necessary to specify "" as the storageClassName
# so that the default storage class won't be used, see
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: btc-mainnet-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400G
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: btc-mainnet
  labels:
    app: blocksayer
spec:
  selector:
    matchLabels:
      app: blocksayer
      tier: btc-mainnet
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: blocksayer
        tier: btc-mainnet
    spec:
      containers:
      - name: btc-mainnet
        image: ccdle12/dbtc:v0.0.6
        ports:
        - containerPort: 8332
          name: btc-mainnet
        env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoin-secret
              key: rpcuser
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcoin-secret
              key: rpcpass
        volumeMounts:
          - mountPath: /data
            name: btc-mainnet-pv
        command: ["/bin/sh"]
        args: ["-c", "bitcoind --datadir=./data"]
      volumes:
        - name: btc-mainnet-pv
          gcePersistentDisk:
            pdName: btc-mainnet-pv
            fsType: ext4