apiVersion: v1
kind: PersistentVolume
metadata:
  name: btc-mainnet-pv
spec:
  storageClassName: btc-mainnet-pv
  capacity:
    storage: 400G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: btc-mainnet-pv
    fsType: ext4
